name: ci

on: [push, pull_request]

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          args: --color always --check lua
